# Generated by Django 2.2.6 on 2019-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_version_name', models.CharField(max_length=30)),
                ('resume_file', models.FileField(upload_to='media')),
            ],
        ),
    ]
