# Generated by Django 2.2.6 on 2019-12-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_resume_res_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='res_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='reume'),
        ),
    ]
