# Generated by Django 2.2.7 on 2019-12-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20191218_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='port_projects',
            fields=[
                ('port_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_name', models.CharField(max_length=50)),
                ('port_date', models.DateField(auto_now_add=True)),
                ('port_description', models.TextField()),
                ('port_image', models.ImageField(upload_to='portfolioimages')),
                ('port_clientname', models.CharField(max_length=50)),
            ],
        ),
    ]
